name: Контроль качества

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sonar:
    uses: autumn-library/workflows/.github/workflows/sonar.yml@main
    with:
      github_repository: autumn-library/autumn-event-publisher
      additional_oscript_packages: autumn
      oscript_version: preview
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
