name: Тестирование

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        oscript_version: ['2.0.0-rc4', 'dev']
    uses: autumn-library/workflows/.github/workflows/test.yml@main
    with:
      oscript_version: ${{ matrix.oscript_version }}
      additional_oscript_packages: autumn
